export const GET_TABLE_DATA = 'GET_TABLE_DATA';
export const GET_TABLE_DATA_SUCCESS = 'GET_TABLE_DATA_SUCCESS';
export const GET_TABLE_DATA_FAILURE = 'GET_TABLE_DATA_FAILURE';
export const FORCE_TABLE_UPDATE = 'FORCE_TABLE_UPDATE';

export const TABLES_STORE_ID = 'tables';
