export default {
  USER_SET: 'USER_SET',
  USER_TOGGLE_LOADING: 'USER_TOGGLE_LOADING',
  USER_SET_MESSAGE_LINKED: 'USER_SET_MESSAGE_LINKED',
  USER_SET_BALANCE: 'USER_SET_BALANCE',
  USER_SET_ID_PROFILE: 'USER_SET_ID_PROFILE',
  USER_SET_INITIAL_USER: 'USER_SET_INITIAL_USER',
};
