export default {
  ERR_SET_APP: 'ERR_SET_APP',
  ERR_SET_AUTH: 'ERR_SET_AUTH',
  ERR_SET_USER: 'ERR_SET_USER',
  ERR_SET_SPOT: 'ERR_SET_SPOT',
  ERR_SET_GRAPHQL: 'ERR_SET_GRAPHQL',
  ERR_SET_NETWORK: 'ERR_SET_NETWORK',
  ERR_RESET_ALL: 'ERR_RESET_ALL',
};
