export enum SelectListName {
  BooleanFilter = 'boolean-filter',
  AnnualReviewStatus = 'annual-review-status',
  BusinessType = 'business-type',
  CTRStatus = 'ctr-status',
  CustomerStatus = 'customer-status',
  EntityType = 'entity-type',
  Frequency = 'frequency',
  InternalTransferStatus = 'internal-transfer-status',
  InternalTransferExportStatus = 'internal-transfer-export-status',
  LicensePosType = 'license-pos-type',
  LicenseSubType = 'license-sub-type',
  LicenseType = 'license-type',
  StartDateType = 'start-date-type',
  DocumentPeriodStatus = 'document-period-status',
  WholesaleReportQueueStatus = 'wholesale-report-queue-status',
  RetailReportQueueStatus = 'retail-report-queue-status',
  TaxReconciliationReportQueueStatus = 'tax-reconciliation-report-queue-status',
  AnnualReviewsStatus = 'annual-review-status',
  StateOfIncorporation = 'state-of-incorporation'
}
