/* eslint-disable max-len */
import React from 'react';
import { View } from 'react-native';

import { Text } from '../../../components';
import s from './styles';

// &#34; = "
// &#39; = '

const TermsOfService = () => (
  <View style={s.container}>
    <Text style={s.text}>Terms and Conditions</Text>
    <Text style={s.text}>This Terms of Use document constitutes an agreement between You and Spectra Networks., Inc (&#34;Us&#34;).  It governs our rights and responsibilities to one another related to use of the Spectra website and Apps (the &#34;Site and Apps&#34;).  It has been created so that we each know what to expect of each other.  When you click &#34;I agree&#34; to these Terms of Use, you agree to be bound by them.  You can cancel your agreement by ceasing to use the Site and Apps and cancelling any registration you maintain with the Site and Apps.</Text>
    <Text style={s.text}>Purpose of the Site and Apps</Text>
    <Text style={s.text}>These Terms of Use should be understood and interpreted in light of the purpose of the Site and Apps.  The Site and Apps are intended to be a place for members of the LGBTQ community to communicate and interact with each other, sharing thoughts, impressions, ideas, images, stories, and information.  By participating in the site and Apps you are expressing an interest in communicating with that community.  You do not need to be a member of the LGBTQ community to use the Site and Apps, but if you do not want to be identified with the LGBTQ community and its issues and concerns, you should probably not use the Site and Apps.</Text>
    <Text style={s.text}>Privacy Policy</Text>
    <Text style={s.text}>Information regarding the types of personal data that we obtain, how we use that data, whether it is shared with others, and your rights with respect to such data, is contained in our Privacy Policy.  The Privacy Policy is part of this Terms of Use.  By agreeing to this Terms of Use you also agree to the terms of the Privacy Policy.  Please review it.  If you do not agree with any aspect of the Privacy Policy, please do not use this site and Apps.</Text>
    <Text style={s.text}>You have the ability to change certain settings in relation to your use of the Site and Apps, such as the settings that control use of cookies.  You also have the right to opt out of certain uses of your data.  Please read the Privacy Policy for further information on those subjects.</Text>
    <Text style={s.text}>Who can use the Site and Apps</Text>
    <Text style={s.text}>Anyone is allowed to use this site and Apps, with certain exceptions.  You are not allowed to use the Site and Apps if you are (1) under 18 years of age or (2) a registered sex offender, or (3) someone who has previously been barred from the Site and Apps.  By agreeing to this Terms of Use you are representing to us that you are not in any of those categories.</Text>
    <Text style={s.text}>Your promises to us</Text>
    <Text style={s.text}>You promise to provide only accurate information on the Site and Apps.  That includes accurate information about yourself, your identity, and the fact that you are 18 or older.</Text>
    <Text style={s.text}>You promise to create only one account under your identity.</Text>
    <Text style={s.text}>You promise to kept your password secure, not to lend your password to others or to use the password of others in accessing the Site and Apps.</Text>
    <Text style={s.text}>We may need to change your username if it is the same or similar to one already in use, or is otherwise confusing or cause problems in the operation of the Site and Apps.</Text>
    <Text style={s.text}>You agree to express yourself with civility and not engage in hateful or hurtful speech or conduct on the Site and Apps.  That includes any speech or conduct that a reasonable person would consider intended to cause anxiety, shame, or fear on the part of someone else.  We want the Site and Apps to be vibrant and interesting, but there is a line between interesting/ edgy, on one side, and hurtful/ hateful/demeaning on the other.  We expect you to try to be aware of where that line is and not cross it.  If you are in doubt, please err on the side of being civil.</Text>
    <Text style={s.text}>You agree not to use the Site and Apps to defame any person, entity or product.  Defamation is a false and negative statement of fact about someone or something (as opposed to a mere expression of a negative opinion).  If you want to express a negative view about a person, entity or product, and are not sure if your language is defamatory please familiarize yourself with the relevant principles and do not cross the line on the Site and Apps.  Even statements that are not technically defamatory, because they are couched as opinions, may violate the rule of civility stated above.</Text>
    <Text style={s.text}>You will not make false or misleading statements on the Site and Apps, or fool or trick people.  You promise not to impersonate another User, assume a false identity, or make it look like content came from someone other than it did.</Text>
    <Text style={s.text}>You agree not to use the Site and Apps to promote prostitution or pandering.  That includes offering your own sexual services or the sexual services of another for any kind of payment.  It does not matter whether the sexual services are between adults or are fully consensual.  It doesn’t even matter whether the conduct it is allowed in the state or other jurisdiction in which you reside.  U.S. law simply renders that whole subject off limits on the Internet, and we have to abide by that law, and we need to ask you to abide by it too while on the Site and Apps.</Text>
    <Text style={s.text}>You agree not to use the Site and Apps to transmit viruses or malware, or to upload any such software to the Site and Apps.  Malware means any software that can disable or impair the operation of the Site and Apps, or the equipment of any other Site and Apps user.</Text>
    <Text style={s.text}>You will be able to read posts made by other users and learn things about them, but you agree not to harvest data about other users using automated processes without our explicit permission.</Text>
    <Text style={s.text}>You agree not to hack the Site and Apps, attempt to obtain access to data that the Site and Apps does not make available in the course of normal operation.</Text>
    <Text style={s.text}>You agree not to use the Site and Apps to violate US, state or other laws.  For example, you agree not to use the Site and Apps to distribute images, music, or other content if someone else has a copyright, without their permission, or to use trademarks without the permission of the trademark holder.  By posting content on the Site and Apps you represent that you have the legal right to post it.  Similarly, you agree not to post information you have an obligation not to reveal, such as trade secrets or confidential information of a business or employer.</Text>
    <Text style={s.text}>You agree not to use the Site and Apps to do things that expose Us to risk civil liability or risk of violating the criminal laws.</Text>
    <Text style={s.text}>Commercial use of the Site and Apps</Text>
    <Text style={s.text}>If you are an advertiser, a business, or anyone else who wants to use the Site and Apps for commercial, as opposed to social, purposes, you must review and agree to our separate Commercial Use Policy.</Text>
    <Text style={s.text}>Remedies for violation of the rules</Text>
    <Text style={s.text}>If you become aware of any User violating the above rules, please report that to us.</Text>
    <Text style={s.text}>We have the right to remove any content that we believe violates the above rules.  We also have the right to disable your account, or bar you from using the Site and Apps if we become are that you are violating any of the above rules.</Text>
    <Text style={s.text}>If you violate any of the above rules we may, at a minimum, terminate your account and bar you from the Site and Apps.</Text>
    <Text style={s.text}>Intellectual property rights in content provided by users</Text>
    <Text style={s.text}>By sharing content on the Site and Apps, you do not transfer any ownership right you have in that content to us.  You do not lose your right to it.  However, by sharing it you do give us the right to use it consistent with the purpose and functioning of the Site and Apps.  When you share content with us (for example, a picture or a story you wrote) you give us a non-exclusive, transferrable, sub-licensable, royalty-free, and worldwide license to host, use, distribute, modify, run, copy, publicly perform or display, translate, and create derivative works of your content.  This permission may be limited by choices you have made in the settings on the Site and Apps.</Text>
    <Text style={s.text}>If you want to terminate our right to do any of the above things, you can delete your content from the Site and Apps.  But please be aware that hitting &#34;delete&#34; will not automatically erase your content everywhere.  It may continue to reside on backup media.  And others may have copied your content off the Site and Apps in the meantime or used it elsewhere on the Site and Apps.  We have no ability to retrieve content that others have copied.</Text>
    <Text style={s.text}>You also understand that if you post content on the Site and Apps other people may forward, copy or otherwise use it.  That is out of our control.</Text>
    <Text style={s.text}>You give us permission to use your name, image, or other information which you provide, or which is apparent from actions you take on the Site and Apps.  For example, if you &#34;like&#34; something on the Site and Apps or make a comment about something, we may display that to others.  We may display your name or image in conjunction with advertising on the Site and Apps.   We do not pay any compensation to users of the Site and Apps for using their name, image or content in this way.  You have the ability to control how information about you is used on the Site and Apps at the Settings page.</Text>
    <Text style={s.text}>If you download any software from the Site and Apps, you give us the right to modify or update that software.</Text>
    <Text style={s.text}>We welcome suggestions and ideas from Users about how to make the Site and Apps better.  However, we do not pay Users for their suggestions or ideas.  Any suggestions or ideas you voluntarily provide to us become our property.</Text>
    <Text style={s.text}>Our intellectual property rights</Text>
    <Text style={s.text}>We have intellectual property rights in various content on the Site and Apps, including software programs, videos, images, music, sounds, logos and brands, text.  You agree not to use our intellectual property outside the way it is intended to be used on the Site and Apps.  You agree not to copy it, forward it to others, or modify it.   You understand that our intellectual property remains our property even though we make it available for you to see, hear and use on the Site and Apps.</Text>
    <Text style={s.text}>Complaints about copyright infringement on the Site and Apps</Text>
    <Text style={s.text}>If you believe someone has posted content on the Site and Apps that infringes your copyright, please contact us at  support@joinspectra.com to receive notification of such complaints.</Text>
    <Text style={s.text}>Changes and updates to these Terms of Use</Text>
    <Text style={s.text}>We may change these Terms of Use in the future.  If we do so, we will give you notice by putting a message on the Site and Apps.  If you do not agree with the new Terms of Use, you may ask for your content to be removed from the Site and Apps and stop using it.</Text>
    <Text style={s.text}>Limitation of our liability</Text>
    <Text style={s.text}>Any product we provide is provided &#34;as is.&#34;  We make no representation or guarantee that any product is or will always be safe, secure, or error free, or that the product will function in the way expected or the way you need it to function to achieve your purposes, or that it will function without delay, imperfections, disruptions, or other problems.  To the extent allowed by law, we make the following disclaimer:</Text>
    <Text style={s.text}>WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON INFRINGEMENT.</Text>
    <Text style={s.text}>You agree that we are not liable for what other people do on the Site and Apps, including other users or vendors.  We cannot control them.</Text>
    <Text style={s.text}>We don’t want to charge a fee for using the Site and Apps.  You agree that our liability is limited to the maximum extent allowed by law.  We will not be obligated to pay for any lost profits, revenues, information, or data lost or harmed in connection with the Site and Apps.  We will not be liable for special, consequential, indirect, exemplary, punitive or incidental damages in any way related to the Site and Apps, even if you or someone else has advised us that such damages are possible or are occurring.  To the extent we are liable for any damages related to the Site and Apps or anything governed by or related to this Terms of Use or the Privacy Policy, you agree that our total aggregate liability (meaning our liability for all claims) will be limited to the amount of money you have paid to us to us to use the Site and Apps in the last twelve months, or $100, whichever is greater.</Text>
    <Text style={s.text}>Dispute resolution</Text>
    <Text style={s.text}>If any dispute arises between us, we agree that we will first give each other written notice of the dispute and then attempt to resolve it through informal discussions.  If, after thirty days, we have not resolved our dispute, either of us may file suit.  We agree that any suit will be filed in and heard by the Circuit Court of Cook County, Illinois or the United States District Court for the Northern District of Illinois.</Text>
    <Text style={s.text}>Miscellaneous provisions</Text>
    <Text style={s.text}>These Terms of Use and the other agreements and standards referenced in this document (including the Privacy Policy) constitute the entire agreement between us.  There documents supersede any prior agreements.</Text>
    <Text style={s.text}>Spectra Networks, Inc., (&#34;Spectra&#34;, &#34;we&#34;) reserves the right to update this Terms and Conditions. Your continued use of the Application after we have posted the revised Policy constitutes your agreement to be bound by the revised Policy.</Text>
    <Text style={s.text}>If any portion of this Terms of Use document is found to be unenforceable, the remainder of it will continue to be enforceable as much as possible.  If you or we fail enforce our rights with respect to one aspect of this Terms of Use, that does not mean we have waived our right to enforce other aspects of the Terms of Use.</Text>
    <Text style={s.text}>The rights you have under this Terms of Use are yours alone.  You may not transfer, sell, assign, or given them to another person.  However, our rights may be assigned to another party in the context of a merger, sale of the business or other change in the business.</Text>
    <Text style={s.text}>This Terms of Use is intended to set out our rights and duties to each other.  It is not intended to benefit any third party or to be enforceable by any third party.</Text>
    <Text style={s.text}>Contact Us</Text>
    <Text style={s.text}>If you have any questions about these Terms, please contact us via email at info@joinspectra.com.</Text>
    <Text>Spectra Networks Inc.</Text>
    <Text>1121 South Michigan Avenue, Suite 191</Text>
    <Text>Chicago IL, 60605</Text>
    <Text style={s.text}>United States</Text>
  </View>
);

export default TermsOfService;
