import { withAppName } from '../utils/helpers/constants';

const screens = {
  AddBusiness: 'AddBusiness',
  AllowLocation: 'AllowLocation',
  Welcome: 'Welcome',
  LocationSettings: 'LocationSettings',
  Connects: 'Connects',
  Drawer: 'Drawer',
  Gallery: 'Gallery',
  EditReview: 'EditReview',
  InviteFriends: 'InviteFriends',
  Map: 'Map',
  MapEvents: 'MapEvents',
  Camera: 'Camera',
  CameraValidate: 'CameraValidate',
  ModalHideLocationItem: 'ModalHideLocationItem',
  Profile: 'Profile',
  ProfileVerification: 'ProfileVerification',
  Other: 'Other',
  PlacesNearList: 'PlacesNearList',
  MyProfile: 'MyProfile',
  MyProfileEdit: 'MyProfileEdit',
  OnBoarding: 'OnBoarding',
  _ProfileEdit: '_ProfileEdit',
  RegisterUser: 'RegisterUser',
  RootLoading: 'RootLoading',
  RoomsList: 'RoomsList',
  SignInWithEmail: 'SignInWithEmail',
  SignUp: 'SignUp',
  SpotReview: 'SpotReview',
  SpotsList: 'SpotsList',
  SpotsPoll: 'SpotsPoll',
  SpotsPollSubmitted: 'SpotsPollSubmitted',
  SpotsNotification: 'SpotsNotification',
  Update: 'Update',
  Users: 'Users',
  VerificationCode: 'VerificationCode',
  SettingGeolocations: 'SettingGeolocations',
  People: 'People',
  BlockedList: 'BlockedList',
  PromoCode: 'PromoCode',
  Album: 'Album',
  AlbumsList: 'AlbumsList',
  CreateEditAlbum: 'CreateEditAlbum',
  Event: 'Event',
  EventsList: 'EventsList',
  CreateEditEvent: 'CreateEditEvent',
  DialogsList: 'DialogsList',
  Dialog: 'Dialog',
  AppInformation: 'AppInformation',
  SelectLegalAgreement: 'SelectLegalAgreement',
  TakingABreak: 'TakingABreak',
  AlbumAccess: 'AlbumAccess',
  ForgotPassword: 'ForgotPassword',
  FriendsList: 'FriendsList',
  PlaceBookmarks: 'PlaceBookmarks',
  PlaceCheckInList: 'PlaceCheckInList',
  CoinsHistory: 'CoinsHistory'
};

export default withAppName(screens);
