export const LOGIN_STATE = 'login';

export const loginActionTypes = {
  LOGIN_UPDATE_PASSWORD_FORM: 'login/UPDATE_PASSWORD_FORM',
  LOGIN_SUBMIT_PASSWORD: 'login/SUBMIT_PASSWORD',
  LOGIN_SUBMIT_PASSWORD_SUCCESS: 'login/SUBMIT_PASSWORD_SUCCESS',
  LOGIN_SUBMIT_PASSWORD_FAILURE: 'login/SUBMIT_PASSWORD_FAILURE',
  LOGIN_SET_MFA_DATA: 'login/SET_MFA_DATA',
  LOGIN_UPDATE_DEVICE_FORM: 'login/UPDATE_DEVICE_FORM',
  LOGIN_CREATE_DEVICE: 'login/CREATE_DEVICE',
  LOGIN_CREATE_DEVICE_SUCCESS: 'login/CREATE_DEVICE_SUCCESS',
  LOGIN_CREATE_DEVICE_FAILURE: 'login/CREATE_DEVICE_FAILURE',
  LOGIN_CHOOSE_MFA_DEVICE: 'login/CHOOSE_MFA_DEVICE',
  LOGIN_SEND_CHALLENGE: 'login/SEND_CHALLENGE',
  LOGIN_RESET_CHALLENGE: 'login/RESET_CHALLENGE',
  LOGIN_RETRY_CHALLENGE: 'login/RETRY_CHALLENGE',
  LOGIN_SEND_CHALLENGE_SUCCESS: 'login/SEND_CHALLENGE_SUCCESS',
  LOGIN_SEND_CHALLENGE_FAILURE: 'login/SEND_CHALLENGE_FAILURE',
  LOGIN_UPDATE_SECURITY_CODE_FORM: 'login/UPDATE_SECURITY_CODE_FORM',
  LOGIN_SEND_SECURITY_CODE: 'login/SEND_SECURITY_CODE',
  LOGIN_SEND_SECURITY_CODE_SUCCESS: 'login/SEND_SECURITY_CODE_SUCCESS',
  LOGIN_SEND_SECURITY_CODE_FAILURE: 'login/SEND_SECURITY_CODE_FAILURE',
  LOGIN_SET_TOKEN: 'login/SET_TOKEN',
  LOGIN_UPDATE_CHOOSE_DEVICE_FORM: 'login/LOGIN_UPDATE_CHOOSE_DEVICE_FORM',
  LOGIN_SUBMIT_CHOOSE_DEVICE_FORM: 'login/LOGIN_SUBMIT_CHOOSE_DEVICE_FORM'
};
